import random 

lst = [
    "The only way to do great work is to love what you do. - Steve Jobs",
    "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost",
    "Be yourself; everyone else is already taken. - Oscar Wilde",
    "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well. - Ralph Waldo Emerson",
    "You miss 100% of the shots you don’t take. - Wayne Gretzky",
    "Life is what happens when you’re busy making other plans. - John Lennon",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. - Ralph Waldo Emerson",
    "You only live once, but if you do it right, once is enough. - Mae West",
    "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
    "It is never too late to be what you might have been. - George Eliot",
    "Life isn't about waiting for the storm to pass, it's about learning to dance in the rain. - Vivian Greene",
    "I think, therefore I am. - René Descartes",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson",
    "Happiness is not something ready-made. It comes from your own actions. - Dalai Lama",
    "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment. - Buddha",
    "The best way to predict the future is to create it. - Abraham Lincoln",
    "Everything has beauty, but not everyone can see it. - Confucius",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "It always seems impossible until it’s done. - Nelson Mandela",
    "You must be the change you wish to see in the world. - Mahatma Gandhi",
    "Life is either a daring adventure or nothing at all. - Helen Keller",
    "To be kind is more important than to be right. - Jodi Picoult",
    "The journey of a thousand miles begins with one step. - Lao Tzu",
    "The only impossible journey is the one you never begin. - Tony Robbins",
    "Life is short, and it is up to you to make it sweet. - Sarah Louise Delany",
    "An unexamined life is not worth living. - Socrates",
    "In the end, it's not the years in your life that count. It's the life in your years. - Abraham Lincoln",
    "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Our lives are what our thoughts make it. - Marcus Aurelius",
    "You don’t have to be great to start, but you have to start to be great. - Zig Ziglar",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "If you can dream it, you can do it. - Walt Disney",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "It’s not whether you get knocked down, it’s whether you get up. - Vince Lombardi",
    "A journey of a thousand miles begins with a single step. - Lao Tzu",
    "The only true wisdom is in knowing you know nothing. - Socrates",
    "Life isn’t about finding yourself. Life is about creating yourself. - George Bernard Shaw",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
    "The secret of getting ahead is getting started. - Mark Twain",
    "It is not length of life, but depth of life. - Ralph Waldo Emerson",
    "You must do the thing you think you cannot do. - Eleanor Roosevelt",
    "I am not afraid of tomorrow, for I have seen yesterday and I love today. - William Allen White",
    "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will. - Vince Lombardi",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "There are no limits to what you can accomplish, except the limits you place on your own thinking. - Brian Tracy",
    "Do what you can, with what you have, where you are. - Theodore Roosevelt",
    "What we think, we become. - Buddha",
    "The mind is everything. What you think you become. - Buddha",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "If you tell the truth, you don't have to remember anything. - Mark Twain",
    "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
    "In the middle of difficulty lies opportunity. - Albert Einstein",
    "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "The way to get started is to quit talking and begin doing. - Walt Disney",
    "Nothing is impossible, the word itself says 'I'm possible'! - Audrey Hepburn",
    "You can't go back and change the beginning, but you can start where you are and change the ending. - C.S. Lewis",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "Our lives are what our thoughts make it. - Marcus Aurelius",
    "In order to succeed, we must first believe that we can. - Nikos Kazantzakis",
    "Act as if what you do makes a difference. It does. - William James",
    "Live life as if everything is rigged in your favor. - Rumi",
    "It’s never too late to be what you might have been. - George Eliot",
    "Life is really simple, but we insist on making it complicated. - Confucius",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson",
    "Success doesn’t come from what you do occasionally, it comes from what you do consistently. - Marie Forleo",
    "Success is the sum of small efforts, repeated day in and day out. - Robert Collier",
    "When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us. - Helen Keller",
    "I would rather die on my feet than live on my knees. - Emiliano Zapata",
    "Dream big and dare to fail. - Norman Vaughan",
    "If you're going through hell, keep going. - Winston Churchill",
    "Success is how high you bounce when you hit bottom. - George S. Patton",
    "The best revenge is massive success. - Frank Sinatra",
    "Success is liking yourself, liking what you do, and liking how you do it. - Maya Angelou",
    "It is not how old you are, but how you are old. - Jules Renard",
    "Everything you can imagine is real. - Pablo Picasso",
    "The best way to predict the future is to invent it. - Alan Kay",
    "Don’t let yesterday take up too much of today. - Will Rogers",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Opportunities don't happen, you create them. - Chris Grosser",
    "Do not wait to strike till the iron is hot, but make it hot by striking. - William Butler Yeats"
]

print(lst[random.randrange(0,len(lst)-1)])